name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install non-Python build dependencies (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get -y install gettext
      - name: Install non-Python build dependencies (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install make
          echo "$(brew --prefix make)/libexec/gnubin" >> \$GITHUB_PATH
      - name: Install Python dependencies
        run: pip install tox build setuptools toml-cli
      - name: Set git identity for tests
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Build
        run: |
          tox
          make build
          pip install .
          new-python-project --help
